# Generated by Django 4.0.4 on 2022-07-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thumbnail', models.ImageField(upload_to='Service_Thumbnail')),
                ('Service_Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Service_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.service_category')),
            ],
        ),
    ]
